Updates from overleaf
Ecdar-SW5/report-common pull request #16
Opened 2022-12-15 08:18 UTC by Laursen79

2022-12-15 08:25 UTC, lugialukas requested changes
Laver denne for at blocke merge da ikke alle kommentarer er resolved så bi ikke skal igennem 2 pull requests, noget fra den første omgang fællesskrivning og så noget i Collaboration review and retrospective

2022-12-15 09:32 UTC, Darkros1245 commented
Operations og query types er done

2022-12-16 08:36 UTC, lugialukas submitted a review, later dismissed
Jeg har fikset kommentarerne så hvis du henter den seneste version så er alt godt

2022-12-16 08:49 UTC, lugialukas approved these changes

2022-12-16 08:49 UTC, merged